In [1]:
import pandas as pd
import os
import numpy as np
import seaborn as sns
import re


os.chdir("C:/Users/user/Perceptron")
os.listdir()

['.ipynb_checkpoints', 'data.xlsx', 'Untitled.ipynb', '~$data.xlsx']

In [2]:
data = pd.read_excel("data.xlsx")
data

Train Instance #  x1  x2
0                 1   1   0
1                 2   0   1
2                 3   1   1
3                 4   0   0

In [3]:
data = data[["x1","x2"]]
data

x1  x2
0   1   0
1   0   1
2   1   1
3   0   0

In [4]:
data["p0"] = -1
data["p1"] = 0
data["p2"] = 0
data["y"] = 0

In [5]:
def xor_gate(x1,x2):
    if x1==x2:
        return 0
    else:
        return 1

In [6]:
def and_gate(x1,x2):
    if (x1 == 1) & (x2 == 1):
        return 1
    else:
        return 0

In [7]:
def or_gate(x1,x2):
    if (x1 == 0) & (x2 == 0):
        return 0
    else:
        return 1

In [8]:
for i in range(data.shape[0]):
    data.iloc[i,3] = and_gate(data.iloc[i,0], data.iloc[i,1])
    data.iloc[i,4] = or_gate(data.iloc[i,0], data.iloc[i,1])

    data.iloc[i,5] = xor_gate(data.iloc[i,0], data.iloc[i,1])

In [9]:
data

x1  x2  p0  p1  p2  y
0   1   0  -1   0   1  1
1   0   1  -1   0   1  1
2   1   1  -1   1   1  0
3   0   0  -1   0   0  0

In [10]:
w = np.array([0,0,0])
w

array([0, 0, 0])

In [11]:
P = np.array(data.iloc[0,2:5]).reshape(-1,1)
P

array([[-1],
       [ 0],
       [ 1]], dtype=int64)

In [12]:
w@P

array([0], dtype=int64)

In [13]:
def z_value(w,data_p):
    P = np.array(data_p).reshape(-1,1)
    return w@P

In [14]:
def step_f(z):
    if z>0:
        return 1
    else:
        return 0

In [15]:
def add_weight(w,lamb,y,y_hat,pi):
    return lamb*(y-y_hat)*np.array(pi)

In [22]:
i = 0
lamb = 0.1
w = np.array([0,0,0]) 

pi = data.iloc[i,2:5]
y = data.iloc[i,5]
z = z_value(w,pi)[0]
y_hat = step_f(z)
w = w + add_weight(w, lamb, y, y_hat, pi)

In [25]:
lamb = 0.1
w = np.array([0,0,0]) 

for i in range(data.shape[0]):
    pi = data.iloc[i,2:5]
    y = data.iloc[i,5]
    z = z_value(w,pi)[0]
    y_hat = step_f(z)
    if y != y_hat:
        w = w + add_weight(w, lamb, y, y_hat, pi)
w

array([ 0. , -0.1,  0. ])

In [27]:
lamb = 0.1
w = np.array([0,0,0]) 

for j in range(4):
    for i in range(data.shape[0]):
        pi = data.iloc[i,2:5]
        y = data.iloc[i,5]
        z = z_value(w,pi)[0]
        y_hat = step_f(z)
        if y != y_hat:
            w = w + add_weight(w, lamb, y, y_hat, pi)
w

array([ 0. , -0.2,  0.1])